DB_URL=jdbc:postgresql://localhost:5432/aniverse
DB_USERNAME=postgres
DB_PASSWORD=password

spring.datasource.url=${secret.DB_URL}
spring.datasource.username=${secret.DB_USERNAME}
spring.datasource.password=${secret.DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver